version: '3'

services:
  server:
    image: kevinduy/reactjs
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    links:
      - mongodb
      
  app:
    image: kevinduy/reactjs
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    tty: true

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017
    volumes:
      - .docker/db:/data/db
